image_size: 256
batch_size: 4
epochs: 5

optimizer: adam

loss_function: weighted_bce_plus_dice

learning_rate: 0.001

input_channels: 6

train_samples_used: 500
validation_samples_used: 100

threshold: 0.3

random_seed: 42